// Generated music tracks (4-minute meditative soundscapes) via ElevenLabs Music.

export interface MusicTrack {
  id: string;
  title: string;
  description: string;
  duration: number; // seconds
  mood: string;
  prompt: string;
  /** Cover-art slug (e.g. "temple-dawn"). Served at /images/music-covers/<cover>.webp. */
  cover?: string;
}

export const MUSIC_TRACKS: MusicTrack[] = [
  {
    id: "lofi-temple-10m",
    title: "Lofi Buddha Temple · 10 min",
    description: "The full lofi temple journey — ten uninterrupted minutes of calm.",
    duration: 600,
    mood: "Sacred",
    cover: "lofi-temple-10m",
    prompt: "Same as lofi-buddha-temple, extended.",
  },
  {
    id: "lofi-temple-20m",
    title: "Lofi Buddha Temple · 20 min",
    description: "Twenty minutes of warm temple lo-fi for deep sleep and rest.",
    duration: 1200,
    mood: "Sacred",
    cover: "lofi-temple-20m",
    prompt: "Same as lofi-buddha-temple, extended.",
  },
  {
    id: "lofi-temple-30m",
    title: "Lofi Buddha Temple · 30 min",
    description: "The full 30-minute temple soundscape — let the night carry you.",
    duration: 1800,
    mood: "Sacred",
    cover: "lofi-temple-30m",
    prompt: "Same as lofi-buddha-temple, extended.",
  },
  {
    id: "midnight-temple",
    title: "Midnight Temple",
    description: "A deep stone temple in the dark of night — tanpura drone, distant bowls, wordless chant.",
    duration: 180,
    mood: "Sacred",
    cover: "midnight-temple",
    prompt: "A deep midnight temple meditation. Ancient stone temple in the dark of night, a continuous low tanpura drone, very distant resonant singing bowls, soft temple bells, slow wordless monk chants in the far distance, faint night wind. Extremely slow, 40-50 BPM, sacred, mysterious, deeply calming. Huge stone chamber reverb. No melody, no drums, no sudden sounds. Minimal, sparse, timeless, instrumental.",
  },
  {
    id: "morning-temple",
    title: "Morning Temple",
    description: "A stone temple at sunrise — golden light, warm bowls, hopeful and serene.",
    duration: 180,
    mood: "Sacred",
    cover: "morning-temple",
    prompt: "A peaceful morning temple meditation. Ancient stone temple at sunrise, soft golden light, a gentle tanpura drone, warm resonant singing bowls, soft temple bells, distant birdsong, faint morning breeze. Slow and hopeful, 50-60 BPM, sacred and serene. Long natural reverb in a stone chamber. No melody, no drums, no sudden sounds. Minimal, warm, uplifting, instrumental.",
  },
  {
    id: "temple-rain",
    title: "Temple Rain",
    description: "Rain on a temple roof, low drone, distant bowl — intimate and cozy.",
    duration: 180,
    mood: "Sacred",
    cover: "temple-rain",
    prompt: "A meditative temple scene with gentle rain. Soft rain falling on a wooden temple roof, a warm low tanpura drone, distant singing bowl, subtle water dripping, calm and intimate atmosphere. Slow and soothing, 45-55 BPM, sacred and cozy. Natural reverb. No melody, no drums, no thunder, no harsh sounds. Minimal, warm, continuous rain texture, instrumental.",
  },
  {
    id: "monks-chant",
    title: "Monk's Chant",
    description: "Wordless vocal drones in a stone temple — ancient and holy.",
    duration: 180,
    mood: "Sacred",
    cover: "monks-chant",
    prompt: "A sacred wordless monk chant meditation. Deep male and female vocal drones, slow wordless chanting in a large stone temple, low tanpura drone, very distant singing bowls, huge natural reverb. Extremely slow, 40-50 BPM, ancient and holy. No melody, no drums, no instruments taking lead, just voices and space. Minimal, timeless, deeply grounding, instrumental.",
  },
  {
    id: "ocean-temple",
    title: "Ocean Temple",
    description: "Waves on a shore, temple tones on the sea breeze — vast and open.",
    duration: 180,
    mood: "Sacred",
    cover: "ocean-temple",
    prompt: "A temple by the ocean meditation. Slow ocean waves rolling onto a shore, a warm tanpura drone, distant resonant singing bowls, soft temple bells carried on the sea breeze. Slow and vast, 45-55 BPM, sacred and open. Natural reverb, spacious. No melody, no drums, no harsh sounds. Minimal, continuous ocean texture blended with temple tones, instrumental.",
  },
  {
    id: "forgotten-temple",
    title: "Forgotten Temple",
    description: "An ancient Himalayan yoga temple at sunrise — tanpura, singing bowls, bansuri and wordless chant.",
    duration: 240,
    mood: "Sacred",
    cover: "forgotten-temple",
    prompt: "A deeply meditative soundscape inspired by an ancient yoga temple hidden high in the Himalayan mountains. Slow, timeless and spiritual. Begin with a deep continuous tanpura drone, distant resonant Tibetan singing bowls, soft temple bells and the warm vibration of a large ceremonial gong. Introduce sparse bansuri bamboo flute phrases with long spaces of silence between notes. Add subtle low male and female wordless vocal drones, resembling distant ancient chanting without recognizable lyrics. Very occasional wooden percussion and soft hand drum pulses that feel like a slow heartbeat. The environment should feel physically present: a huge stone temple chamber, long natural reverberation, faint mountain wind through open temple doors, distant flowing water and occasional subtle birds far outside. Extremely slow tempo, 45-55 BPM. Ancient, sacred, mysterious, grounding, peaceful, introspective. Organic, warm, spacious, imperfect, human. Gentle and consistent dynamics, minimal and slowly evolving structure, wordless atmospheric chanting. Avoid modern synth leads, pop melodies, EDM, strong drums, cinematic trailers, dramatic crescendos. The feeling of entering a forgotten mountain yoga temple at sunrise and remaining there indefinitely.",
  },
  {
    id: "ocean-depth",
    title: "Ocean Depth",
    description: "Slow ambient drift over deep water — distant whales, soft pads, endless horizon.",
    duration: 240,
    mood: "Deep",
    cover: "ocean-depth",
    prompt: "A deep underwater ambient meditation. Very slow, dark and vast. Soft low ambient pads drifting like ocean currents, distant whale song, gentle deep water movement, slow breathing textures. Huge, spacious, weightless. No drums, no melody, just slow evolving atmosphere. Perfect for deep meditation and sleep.",
  },
  {
    id: "rainy-kyoto",
    title: "Rainy Kyoto",
    description: "Rain on a temple roof, a distant koto, warm low fire — a quiet Japanese evening.",
    duration: 240,
    mood: "Nostalgic",
    cover: "rainy-kyoto",
    prompt: "A quiet rainy evening in Kyoto. Gentle rain falling on a wooden temple roof, a sparse distant koto plucking a few notes, warm low drone, soft wooden percussion, a faint crackling fire. Calm, nostalgic, intimate, warm. Slow tempo, minimal, with long silences. No drums, no strong melody.",
  },
  {
    id: "lo-fi-focus",
    title: "Lo-fi Focus",
    description: "Soft warm lo-fi for deep work — mellow pads, gentle keys, no harsh edges.",
    duration: 240,
    mood: "Focus",
    cover: "lo-fi-focus",
    prompt: "Soft smooth lo-fi ambient music for deep focus and studying. Gentle warm pads, slow minimal piano, a very soft muffled beat, warm vinyl texture, subtle tape hiss. Clean production, no distortion, no harsh sounds, no vocals, no sudden changes. Calm, cozy, smooth, relaxing. Perfect background for deep work and concentration. Low tempo, steady, consistent dynamics.",
  },
  {
    id: "lofi-buddha-temple",
    title: "Lofi Buddha Temple",
    description: "Peaceful lo-fi from a quiet temple — a bell, soft keys, and a warm beat.",
    duration: 240,
    mood: "Sacred",
    cover: "lofi-buddha-temple",
    prompt: "A peaceful lo-fi hip hop instrumental inspired by a quiet Buddhist temple. Begins with a single clear, resonant temple bell chime that rings out and gently fades. Warm mellow lo-fi beat, soft vinyl crackle, smooth rounded bass, gentle electric piano and Rhodes chords, sparse singing bowls, soft temple bells, a subtle warm drone like a distant tanpura. Calm, meditative, spiritual, cozy, nostalgic. No vocals, no harsh sounds, no distortion, no sudden changes. Slow tempo around 75 BPM. Clean smooth production. Perfect for deep focus, study and relaxation.",
  },

  {
    id: "moon-tide-drift",
    title: "Moon Tide Drift",
    description: "Slow ambient drift under moonlight — soft pads, weightless floating over a dark tide.",
    duration: 600,
    mood: "Dreamy",
    cover: "moon-tide-drift",
    prompt: "Dreamy beatless ambient, slowly evolving warm drone, airy synth pads, deep spacious reverb, long echo tails, weightless floating. No drums, no percussion, no beat, no melody, no song structure, continuous serene flow.",
  },
  {
    id: "weightless-drift",
    title: "Weightless Drift",
    description: "Weightless floating — airy pads, endless horizon, no edges, no ground.",
    duration: 600,
    mood: "Dreamy",
    cover: "weightless-drift",
    prompt: "Weightless floating ambient, airy synth pads, deep spacious reverb, slow evolving textures. Beatless, no drums, no melody, continuous serene drift.",
  },
  {
    id: "stone-bowl-garden",
    title: "Stone Bowl Garden",
    description: "A zen stone garden at dusk — resonant bowls, soft water, warm grounding drone.",
    duration: 600,
    mood: "Dreamy",
    cover: "stone-bowl-garden",
    prompt: "Zen stone garden at dusk, resonant singing bowls, soft water trickle, warm low drone, slow and grounding. Beatless, no drums, no melody, minimal sparse textures.",
  },
  {
    id: "moonlit-bamboo-drift",
    title: "Moonlit Bamboo Drift",
    description: "Moonlit bamboo grove — breathy flute, airy pads, gentle wind through leaves.",
    duration: 600,
    mood: "Dreamy",
    cover: "moonlit-bamboo-drift",
    prompt: "Moonlit bamboo grove, breathy bamboo flute with long sustained notes, soft airy pads, gentle wind through leaves. Beatless, no drums, floating, serene, continuous flow.",
  },
  {
    id: "moonlit-ruins",
    title: "Moonlit Ruins",
    description: "Abandoned temple ruins under moonlight — echoing stone hall, distant bowls, forgotten and timeless.",
    duration: 600,
    mood: "Dreamy",
    cover: "moonlit-ruins",
    prompt: "Abandoned ancient temple ruins under moonlight, empty echoing stone hall, distant resonant bowls, slow evolving warm drone. Beatless, no drums, no melody, forgotten and timeless atmosphere.",
  },

  {
    id: "cloud-drift",
    title: "Cloud Drift",
    description: "Weightless floating through soft clouds — airy pads, deep reverb, no ground.",
    duration: 600,
    mood: "Dreamy",
    cover: "cloud-drift",
    prompt: "Beatless floating ambient, slowly evolving warm drone, airy synth pads, deep spacious reverb, long echo tails, weightless floating through soft clouds.",
  },
  {
    id: "cloud-drift-2",
    title: "Cloud Drift II",
    description: "A second take on floating through clouds — a softer, airier variation.",
    duration: 600,
    mood: "Dreamy",
    cover: "cloud-drift-2",
    prompt: "Beatless floating ambient through soft clouds (second variation), airy pads, deep reverb.",
  },
  {
    id: "celestial-drift",
    title: "Celestial Drift",
    description: "Ethereal drift in a vast open night sky — soft pads, slow breathing textures.",
    duration: 600,
    mood: "Dreamy",
    cover: "celestial-drift",
    prompt: "Ethereal weightless drift, soft airy pads, rising and falling textures like slow breathing, vast open night sky.",
  },
  {
    id: "celestial-drift-2",
    title: "Celestial Drift II",
    description: "A second take on the celestial sky — a calmer, deeper variation.",
    duration: 600,
    mood: "Dreamy",
    cover: "celestial-drift-2",
    prompt: "Ethereal weightless drift in a vast night sky (second variation), soft pads, deep reverb.",
  },
  {
    id: "temple-flute",
    title: "Temple Flute",
    description: "An abandoned temple — breathy bamboo flute, distant bowls, forgotten and timeless.",
    duration: 600,
    mood: "Dreamy",
    cover: "temple-flute",
    prompt: "Abandoned ancient temple, breathy bamboo flute, distant singing bowls, slow drone, forgotten and timeless.",
  },
  {
    id: "temple-flute-2",
    title: "Temple Flute II",
    description: "A second take on the temple flute — a deeper, more echoing variation.",
    duration: 600,
    mood: "Dreamy",
    cover: "temple-flute-2",
    prompt: "Abandoned ancient temple, breathy bamboo flute (second variation), distant bowls, slow drone.",
  },
  {
    id: "temple-dawn",
    title: "Temple Dawn",
    description: "An abandoned temple at first light — golden rays through broken columns, breathy flute, forgotten and serene.",
    duration: 232,
    mood: "Dreamy",
    cover: "temple-dawn",
    prompt: "Abandoned ancient temple at dawn, first golden light through broken columns, breathy bamboo flute, distant bowls, slow warm drone.",
  },
  {
    id: "temple-dawn-2",
    title: "Temple Dawn II",
    description: "A second take on the temple at dawn — a softer, warmer variation.",
    duration: 228,
    mood: "Dreamy",
    cover: "temple-dawn-2",
    prompt: "Abandoned ancient temple at dawn (second variation), golden sunrise rays, moss on weathered stone.",
  },
  {
    id: "temple-night",
    title: "Temple Night",
    description: "An abandoned temple in the deep of night — moonless sky, echoing stone, a distant lantern glow.",
    duration: 208,
    mood: "Dreamy",
    cover: "temple-night",
    prompt: "Abandoned ancient temple in the deep of night, moonless sky, cold blue-black stone chamber, distant warm lantern.",
  },
  {
    id: "temple-night-2",
    title: "Temple Night II",
    description: "A second take on the night temple — faint starlight, long shadows, a single glowing bowl.",
    duration: 243,
    mood: "Dreamy",
    cover: "temple-night-2",
    prompt: "Moonless night over an abandoned temple courtyard, faint starlight, deep shadows, a single warm glowing bowl.",
  },
  {
    id: "temple-mist",
    title: "Temple Mist",
    description: "An abandoned mountain temple in the mist — breathy flute, soft wind, damp stone, forgotten and still.",
    duration: 229,
    mood: "Dreamy",
    cover: "temple-mist",
    prompt: "Abandoned mountain temple in mist, breathy bamboo flute, soft wind through broken doors, damp stone.",
  },
  {
    id: "temple-mist-2",
    title: "Temple Mist II",
    description: "A second take on the misty temple — a glowing bowl at dusk, clouds between ruined pillars.",
    duration: 239,
    mood: "Dreamy",
    cover: "temple-mist-2",
    prompt: "Misty mountain temple at dusk, clouds between ruined pillars, a lone singing bowl glowing softly.",
  },
  {
    id: "temple-rain-hall",
    title: "Temple Rain Hall",
    description: "Rain on the temple roof — water dripping into dark pools, a warm lantern, intimate and sheltering.",
    duration: 214,
    mood: "Dreamy",
    cover: "temple-rain-hall",
    prompt: "Abandoned ancient temple with gentle rain on the stone roof, water dripping into dark pools, warm lantern.",
  },
  {
    id: "temple-rain-hall-2",
    title: "Temple Rain Hall II",
    description: "A second take on the rain hall — puddles reflecting golden light, the shelter of old stone.",
    duration: 229,
    mood: "Dreamy",
    cover: "temple-rain-hall-2",
    prompt: "Rain inside an abandoned temple hall, puddles reflecting warm golden light, dripping stone, sheltering.",
  },
  {
    id: "yogi-temple-dawn",
    title: "Yogi Temple Dawn",
    description: "A lofi yogi meditation at first light — breathy flute, warm drone, forgotten stone in the mist.",
    duration: 222,
    mood: "Dreamy",
    cover: "temple-dawn",
    prompt: "Lofi yogi temple meditation at dawn, abandoned temple, breathy flute, tanpura drone, singing bowls.",
  },
  {
    id: "yogi-temple-ember",
    title: "Yogi Temple Ember",
    description: "A lofi yogi meditation wrapped in deep crimson — breathy flute, warm pads, grounding and calm.",
    duration: 228,
    mood: "Dreamy",
    cover: "temple-red-velvet",
    prompt: "Lofi yogi temple meditation, deep crimson cloth, breathy flute, warm drone, singing bowls.",
  },
  {
    id: "yogi-temple-saffron",
    title: "Yogi Temple Saffron",
    description: "A sun-faded saffron meditation — breathy flute, tanpura drone, warm and slow.",
    duration: 224,
    mood: "Dreamy",
    cover: "temple-saffron",
    prompt: "Lofi yogi temple meditation, sun-faded saffron cloth, breathy flute, tanpura drone, singing bowls.",
  },
  {
    id: "yogi-temple-mist",
    title: "Yogi Temple Mist",
    description: "A lofi yogi meditation in thick mist — flute drifting through fog, damp stone, deep calm.",
    duration: 239,
    mood: "Dreamy",
    cover: "temple-mist",
    prompt: "Lofi yogi temple meditation in mist, abandoned mountain temple, breathy flute, warm drone.",
  },
  {
    id: "yogi-temple-night",
    title: "Yogi Temple Night",
    description: "A moonlit lofi yogi meditation — flute, tanpura, temple bells in the dark, restful and calm.",
    duration: 204,
    mood: "Dreamy",
    cover: "temple-night",
    prompt: "Lofi yogi temple meditation at night, abandoned temple under a full moon, breathy flute, bells.",
  },
  {
    id: "yogi-temple-checkered",
    title: "Yogi Temple Checkered",
    description: "A handwoven lofi meditation — flute, warm drone, distant bowls, timeless and calming.",
    duration: 244,
    mood: "Dreamy",
    cover: "temple-checkered",
    prompt: "Lofi yogi temple meditation, handwoven checkered cloth, breathy flute, warm drone, singing bowls.",
  },
  {
    id: "yogi-temple-dawn-2",
    title: "Yogi Temple Dawn II",
    description: "A second take on the lofi dawn meditation — softer flute, deeper stillness.",
    duration: 214,
    mood: "Dreamy",
    cover: "temple-dawn-2",
    prompt: "Lofi yogi temple meditation at dawn (second variation), abandoned temple, breathy flute, tanpura drone.",
  },
  {
    id: "yogi-temple-ember-2",
    title: "Yogi Temple Ember II",
    description: "A second take wrapped in deep crimson — warmer pads, slower breathing.",
    duration: 224,
    mood: "Dreamy",
    cover: "temple-red-velvet-2",
    prompt: "Lofi yogi temple meditation, deep crimson cloth (second variation), breathy flute, warm drone.",
  },
  {
    id: "yogi-temple-saffron-2",
    title: "Yogi Temple Saffron II",
    description: "A second take on the sun-faded saffron — gentler flute, longer silences.",
    duration: 234,
    mood: "Dreamy",
    cover: "temple-saffron-2",
    prompt: "Lofi yogi temple meditation, sun-faded saffron cloth (second variation), breathy flute, tanpura drone.",
  },
  {
    id: "yogi-temple-mist-2",
    title: "Yogi Temple Mist II",
    description: "A second take in thick mist — flute drifting lower through fog.",
    duration: 220,
    mood: "Dreamy",
    cover: "temple-mist-2",
    prompt: "Lofi yogi temple meditation in mist (second variation), abandoned mountain temple, breathy flute.",
  },
  {
    id: "yogi-temple-night-2",
    title: "Yogi Temple Night II",
    description: "A second moonlit take — softer bells, deeper night calm.",
    duration: 209,
    mood: "Dreamy",
    cover: "temple-night-2",
    prompt: "Lofi yogi temple meditation at night (second variation), abandoned temple under a full moon, bells.",
  },
  {
    id: "yogi-temple-checkered-2",
    title: "Yogi Temple Checkered II",
    description: "A second handwoven take — warmer drone, more distant bowls.",
    duration: 238,
    mood: "Dreamy",
    cover: "temple-checkered-2",
    prompt: "Lofi yogi temple meditation, handwoven checkered cloth (second variation), breathy flute, warm drone.",
  },
  {
    id: "moonlit-bamboo-drift-2",
    title: "Moonlit Bamboo Drift II",
    description: "A second take on the moonlit bamboo grove — a deeper, airier variation.",
    duration: 240,
    mood: "Dreamy",
    cover: "moonlit-bamboo-drift-2",
    prompt: "Moonlit bamboo grove (second variation), breathy bamboo flute with long sustained notes, airy pads, wind.",
  },
  {
    id: "moonlit-ruins-2",
    title: "Moonlit Ruins II",
    description: "A second take on the abandoned ruins — colder stone, longer echoes.",
    duration: 240,
    mood: "Dreamy",
    cover: "moonlit-ruins-2",
    prompt: "Abandoned ancient temple ruins under moonlight (second variation), empty echoing stone hall, distant bowls.",
  },
  {
    id: "stone-bowl-garden-2",
    title: "Stone Bowl Garden II",
    description: "A second take on the zen garden — softer water, warmer drone.",
    duration: 240,
    mood: "Dreamy",
    cover: "stone-bowl-garden-2",
    prompt: "Zen stone garden at dusk (second variation), resonant singing bowls, soft water trickle, warm low drone.",
  },
];
