/**
 * Premium workshops — multi-session guided series.
 *
 * Same shape as meditations.ts so the existing player and generation script
 * pick them up unchanged. Each session targets ~20 minutes of voice + pauses.
 */
import type { Experience } from "./experiences";

export type Workshop = {
  id: string;
  title: string;
  description: string;
  duration: string;
  theme: string;
  category: "focus" | "breathe" | "sleep" | "relax";
  background: string;
  /** Seconds of silence after the chime, before the voice begins — lets the
   *  user put the device down and settle in. */
  introPause?: number;
  segments: { text: string; pauseAfter: number }[];
};

export const WORKSHOPS: Workshop[] = [
  {
    id: "deep-sleep-reset-1",
    title: "Deep Sleep Reset — Night 1: Letting Go",
    description:
      "The first night of the Deep Sleep Reset. Release the weight of the day and let the body sink toward rest.",
    duration: "10 min",
    theme: "Deep Sleep Reset",
    category: "sleep",
    background: "off",
    introPause: 25,
    segments: [
      {
        text: "Welcome. This is the first night of your deep sleep reset. Find a comfortable position, lying down if you can. Let your arms rest at your sides, palms open. Allow the room to be as dark and quiet as it needs to be. There is nothing you need to fix, nothing you need to hold. This time belongs only to you.",
        pauseAfter: 14,
      },
      {
        text: "Take one slow breath in through the nose. Let it travel all the way down into the belly. And now breathe out, a little longer than the breath in. Feel the breath soften the muscles around your eyes, your jaw, your brow. You are allowed to arrive slowly. There is no rush.",
        pauseAfter: 16,
      },
      {
        text: "Now bring a gentle attention to the weight of your body. Feel where it meets the bed, the floor, the surface beneath you. Notice the places where you are being held. The back of your head. Your shoulder blades. Your hips. Your heels. You do not need to hold yourself up tonight. Let the ground take the weight.",
        pauseAfter: 18,
      },
      {
        text: "Soften your face. Let the forehead go smooth. Let the space between your eyebrows release. Unclench the jaw, and let the tongue rest gently behind the lower teeth. Let the lips part slightly. With every breath out, a little more of the day leaves you.",
        pauseAfter: 14,
      },
      {
        text: "Move your attention down to your neck and your shoulders. If there is any tightness here, do not fight it. Simply breathe into it. Imagine the breath flowing down into the shoulders like warm water, and as you exhale, the shoulders melt a little further into the bed.",
        pauseAfter: 16,
      },
      {
        text: "Now your arms, heavy and warm. Your hands, soft and still. Feel the gentle heaviness of them as they rest. Then your chest and your belly, rising and falling without any effort. You are not doing the breathing. The breath is doing you. Let it.",
        pauseAfter: 16,
      },
      {
        text: "Let your awareness travel down through your hips, heavy and sinking. Your thighs, your knees, your calves. Your ankles, and at last your feet, growing distant and warm. Your whole body is now a single field of softness, quiet and still.",
        pauseAfter: 18,
      },
      {
        text: "If a thought appears, let it be like a cloud passing across a wide, dark sky. You do not need to chase it, and you do not need to push it away. You simply watch it drift, and then return your attention to the breath, moving slow and steady in the dark.",
        pauseAfter: 20,
      },
      {
        text: "Now I want you to picture a place where you have felt completely safe. It may be a room from childhood, a quiet shore, a warm garden at dusk. See it softly, in gentle colours. Hear it, the way it sounds when everything else has gone quiet. You are there now, and you are safe.",
        pauseAfter: 18,
      },
      {
        text: "In this place, there is a soft surface waiting for you — a bed, a blanket in the grass, the warm sand. You lie down upon it, and it receives you completely. It is made for exactly your shape. Sink into it. Let it hold every part of you, without you having to try.",
        pauseAfter: 18,
      },
      {
        text: "Listen to the sound around you. A quiet wave in the distance, or the slow rustle of leaves, or a silence so deep it hums. Let that sound become the rhythm of your breath. Each wave, each whisper, each rise and fall, drawing you deeper and deeper into rest.",
        pauseAfter: 20,
      },
      {
        text: "With every breath out, you are letting go of something you no longer need to carry. The conversations that circled and circled. The list of things for tomorrow. The small tensions you have held in your body all day. One by one, they loosen, and they float away, into the dark.",
        pauseAfter: 20,
      },
      {
        text: "There is nothing more to do. No next step, no place to be. The day has already been lived, and it is complete. You have done enough. You have been enough. You can lay down the weight now, and let the night take over.",
        pauseAfter: 22,
      },
      {
        text: "Feel how heavy the body has become, and how light the mind. The two are drifting apart, gently. The body is a warm, still thing, resting in the earth. The mind is a soft light, rising. Sleep is not something you need to find. It is finding you, slowly, from the inside.",
        pauseAfter: 22,
      },
      {
        text: "If you are still awake, that is perfectly fine. There is no test here, and no failing. Simply remain in this quiet place, breathing, listening, letting go. You are already exactly where you need to be.",
        pauseAfter: 24,
      },
      {
        text: "I will be quiet now, and leave you with the sound, and the breath, and the dark. Stay here as long as you like. Let yourself drift. Goodnight.",
        pauseAfter: 0,
      },
    ],
  },

  {
    id: "deep-sleep-reset-2",
    title: "Deep Sleep Reset — Night 2: Softening the Body",
    description:
      "The second night. Sink deeper into the body and let every surface soften toward sleep.",
    duration: "10 min",
    theme: "Deep Sleep Reset",
    category: "sleep",
    background: "off",
    introPause: 25,
    segments: [
      { text: "Welcome back. This is the second night of your deep sleep reset. Find your way into bed, and let yourself settle into the same familiar position, the one your body already knows. There is nowhere else to be, and nothing else to prepare. Tonight is simply a continuation of the rest you have already begun.", pauseAfter: 14 },
      { text: "Take one slow breath in through the nose, and let it out with a soft sigh, as if you were letting the whole day pour out of you. Feel how natural that sigh is, how the body knows exactly what to do. You do not have to manage this. You only have to allow it.", pauseAfter: 16 },
      { text: "Now bring your attention to the skin, the outer surface of you. Notice how it rests against the sheets, the pillow, the cool air of the room. Feel the places where the body touches something, and the places where it touches nothing at all. You are held on every side.", pauseAfter: 16 },
      { text: "Let your face go completely soft. The forehead, smooth and wide. The eyes, heavy and still beneath their lids. The cheeks, loose. The jaw, unclenched, so that the teeth no longer touch, and the lips rest gently apart.", pauseAfter: 15 },
      { text: "Now soften the throat, the place where so much of the day gathers, where words are formed and held back. Let it open and relax. Then the neck, and the shoulders, letting them drop away from the ears, falling like water over stone.", pauseAfter: 16 },
      { text: "Bring your awareness to your arms, and simply let them be heavy. Feel the weight of each hand, the palms open and soft, the fingers curling slightly, as if they had already fallen asleep without you.", pauseAfter: 16 },
      { text: "Now the chest and the belly, rising and falling on their own, without any effort from you. Feel the breath moving here like a slow tide, in and out, and let each exhale carry a little more tension away from the body.", pauseAfter: 16 },
      { text: "Let your attention drift down through the hips and the legs, growing warm and distant. The thighs, the knees, the calves, all sinking into the bed. And the feet, far away now, as soft and still as the rest of you.", pauseAfter: 18 },
      { text: "By now the whole body has begun to feel like one single, quiet surface, a field of softness with no edges and no effort. And it is enough to simply be here, resting inside it, letting it hold you.", pauseAfter: 18 },
      { text: "If any part of you still feels tight, do not struggle against it. Simply breathe in its direction, and imagine the breath arriving there like warm light, loosening whatever it touches. There is no hurry. The body will let go when it is ready.", pauseAfter: 18 },
      { text: "Notice how the mind, too, has begun to soften, the edges of your thoughts blurring gently, like the last light of evening. You do not have to follow any of them. They can come and go on their own, like slow clouds across a dim sky.", pauseAfter: 20 },
      { text: "Feel the heaviness deepening, a pleasant weight settling over you, warm as a blanket and just as safe. It is the body's own way of saying that it is time, that you are allowed to stop holding on, that you can let yourself be carried.", pauseAfter: 20 },
      { text: "There is nothing you need to do now, and nothing you need to remember. The day is already complete, and you are already here, exactly where you belong. Let the night close around you, soft and certain.", pauseAfter: 22 },
      { text: "With every breath out, allow a little more of yourself to sink into the bed, until you can no longer tell where you end and the sheets begin. You are not leaving anything behind. You are simply arriving, more and more deeply, into rest.", pauseAfter: 22 },
      { text: "If you are still awake, that is perfectly fine. There is no goal here, and no one keeping score. Just keep breathing, slow and even, and let the softness do the work for you.", pauseAfter: 22 },
      { text: "I will be quiet now, and leave you to the dark and the quiet and the gentle weight of sleep. Stay here as long as you like. Let yourself drift. Goodnight.", pauseAfter: 0 },
    ],
  },
  {
    id: "deep-sleep-reset-3",
    title: "Deep Sleep Reset — Night 3: Quieting the Mind",
    description:
      "The third night. Learn to let the thinking mind wind down and rest like the body.",
    duration: "10 min",
    theme: "Deep Sleep Reset",
    category: "sleep",
    background: "off",
    introPause: 25,
    segments: [
      { text: "Welcome back. This is the third night of your deep sleep reset. Settle into bed, and let your body find its place, as if it had been waiting for this all day. Tonight we turn our attention gently toward the mind, the part of you that has been busy, and invite it, too, to rest.", pauseAfter: 14 },
      { text: "Take a slow breath in, and let it out through the mouth with a long, soft sigh. Feel the day begin to loosen its grip, and notice how, for just a moment, the thinking mind goes quiet. That quiet is always there, underneath everything. Tonight, we rest in it.", pauseAfter: 16 },
      { text: "Bring your attention to your thoughts, not to stop them, but simply to watch them, the way you might watch leaves drifting on a slow river. They come, and they go. You are not the thoughts. You are the one watching them.", pauseAfter: 18 },
      { text: "If a thought about tomorrow appears, let it pass by. If a memory of today appears, let it pass by too. You do not have to fix anything, resolve anything, or hold onto anything. The mind can rest from its work now.", pauseAfter: 18 },
      { text: "Feel the breath, moving slow and steady in the background, like a gentle current that has always been there. Each time you notice the mind wandering, do not scold it. Simply return, kindly, to the breath, and to the quiet.", pauseAfter: 17 },
      { text: "Notice that the more you watch the thoughts, the quieter they become, the way a lake grows still when the wind dies down. The surface of the mind begins to smooth, and the depths below become clear and calm.", pauseAfter: 18 },
      { text: "Let the body sink deeper into the bed, and let the mind sink too, into a soft, warm drowsiness. You do not have to stay alert, or hold anything together. The night will hold it all for you.", pauseAfter: 18 },
      { text: "Imagine the mind as a room, and one by one, the lights in that room are being turned down. The thoughts grow softer, dimmer, until only a faint, gentle glow remains, and then even that begins to fade.", pauseAfter: 20 },
      { text: "There is nowhere you need to be, and nothing you need to solve. The questions that felt so urgent today can wait until the morning. They will still be there, but you do not have to carry them into the night.", pauseAfter: 20 },
      { text: "With each breath out, feel the mind let go of a little more of its holding. The lists, the plans, the small worries — they loosen, and they float away, like lanterns released into the dark.", pauseAfter: 20 },
      { text: "You are entering the space between waking and sleeping, where the mind is no longer thinking, and not yet dreaming. It is a soft, borderless place, and it is safe to be here. Let yourself rest on its edge.", pauseAfter: 20 },
      { text: "If sleep comes, let it come. If it does not, that is all right too. There is no effort required, and no performance. Just the quiet, and the breath, and the slow unspooling of the day.", pauseAfter: 22 },
      { text: "Feel how still everything has become. The body, heavy and warm. The mind, like a calm sea. The breath, moving in and out, slow as the tide, drawing you gently toward the shore of sleep.", pauseAfter: 22 },
      { text: "You have carried enough for one day. You are allowed to set it all down now, to close the door on the thinking mind, and to rest. Nothing will be lost. Everything that matters will still be here in the morning.", pauseAfter: 22 },
      { text: "Stay here, in this quiet, for as long as you like. You are not waiting for anything. You are already where you need to be. Let the night gather you up, soft and complete.", pauseAfter: 22 },
      { text: "I will be quiet now, and leave you with the breath and the stillness and the dark. Let yourself drift. Goodnight.", pauseAfter: 0 },
    ],
  },
  {
    id: "deep-sleep-reset-4",
    title: "Deep Sleep Reset — Night 4: The Breath of Sleep",
    description:
      "The fourth night. Follow the breath as it slows, deepens, and carries you into rest.",
    duration: "10 min",
    theme: "Deep Sleep Reset",
    category: "sleep",
    background: "off",
    introPause: 25,
    segments: [
      { text: "Welcome back. This is the fourth night of your deep sleep reset. Settle in, and let the body arrange itself into rest, the way it knows how. Tonight, we let the breath become the guide, and follow it all the way down into sleep.", pauseAfter: 14 },
      { text: "Take one slow, full breath in through the nose, and let it go with a soft, audible sigh. Notice the sound of it, how the breath is like a small wave arriving on a shore, and then receding. You do not have to shape it. Just follow it.", pauseAfter: 16 },
      { text: "Now simply observe the breath, exactly as it is, without changing a thing. Feel the cool air at the nostrils, the gentle rise of the chest, the soft fall of the belly. The breath has been doing this all your life, without ever asking your permission.", pauseAfter: 16 },
      { text: "With every breath out, let it become a little longer, a little slower, a little deeper, as if the body itself were winding down. You are not forcing anything. You are only noticing the natural rhythm, and letting it deepen on its own.", pauseAfter: 17 },
      { text: "Feel the pause at the end of each exhale, the tiny stillness before the next breath arrives. Rest in that pause. It is a doorway, and each time you pass through it, you sink a little deeper into the quiet.", pauseAfter: 18 },
      { text: "Let the breath travel down through the whole body, from the crown of the head to the soles of the feet. Imagine it as a slow, warm current, washing through you, softening everything it touches.", pauseAfter: 18 },
      { text: "The body grows heavy now, warm and still, and the breath becomes so soft you can barely hear it. It is no longer something you are doing. It is something that is happening to you, like sleep itself, arriving from the inside.", pauseAfter: 18 },
      { text: "Notice how the rhythm of the breath begins to match the rhythm of the night, slow and even, like the rise and fall of a sleeping ocean. You are in tune with something much larger than yourself now.", pauseAfter: 18 },
      { text: "If a thought drifts in, let it ride out on the next exhale. You do not have to hold it, or answer it. Just breathe it away, and return to the soft, steady tide of the breath.", pauseAfter: 20 },
      { text: "With each cycle, the breath carries you a little further from the day, and a little closer to the edge of sleep. You are not making this happen. You are simply allowing it, the way you allow a wave to carry you.", pauseAfter: 20 },
      { text: "Feel the chest rise, and fall. The belly, rise and fall. The whole body, breathing as one, slow and luminous and at peace. This is the breath of sleep, and it is already yours.", pauseAfter: 20 },
      { text: "There is nothing to do but breathe, and even the breathing is doing itself. You can let go of the need to control it, to watch it, to manage anything at all. The breath will keep you safe while you rest.", pauseAfter: 22 },
      { text: "Let the breath grow so soft that it is almost silent, and let the silence grow so deep that it is almost like sleep. You are hovering now, on the very edge, weightless and warm.", pauseAfter: 22 },
      { text: "If you are still awake, simply remain with the breath, and let it be enough. You are not failing at anything. You are resting, and resting is enough. The night is long, and it is all for you.", pauseAfter: 22 },
      { text: "Feel the breath, slow as a sleeping tide. Feel the body, heavy and warm. Feel the dark, soft and close. There is nothing more you need to do. Just breathe, and let go.", pauseAfter: 22 },
      { text: "I will be quiet now, and leave you with the breath, the tide, and the dark. Let yourself drift. Goodnight.", pauseAfter: 0 },
    ],
  },
  {
    id: "deep-sleep-reset-5",
    title: "Deep Sleep Reset — Night 5: The Safe Place",
    description:
      "The fifth night. Return to a place of deep safety and let it hold you into sleep.",
    duration: "10 min",
    theme: "Deep Sleep Reset",
    category: "sleep",
    background: "off",
    introPause: 25,
    segments: [
      { text: "Welcome back. This is the fifth night of your deep sleep reset. Settle into bed, and let the room grow soft around you. Tonight, we travel to a place of safety, a place that exists only for you, and we let it hold you while you rest.", pauseAfter: 14 },
      { text: "Take a slow breath in, and let it out gently, allowing the body to release into the bed. Feel the covers around you, the pillow beneath your head. You are already safe. Everything else can wait.", pauseAfter: 16 },
      { text: "Now close your eyes, if you have not already, and bring to mind a place where you have felt completely, utterly safe. It may be a real place, or one you have only imagined. There is no wrong answer. Let it arise on its own.", pauseAfter: 17 },
      { text: "See this place softly, in gentle colours, as if through the haze of a warm evening. Do not force the details. Let them come slowly — a shape, a texture, a familiar light. You are arriving there now, and you are welcome.", pauseAfter: 18 },
      { text: "Listen to the sounds of this place. The quiet hush of it, the soft rhythm of whatever is near. Perhaps it is the sound of rain on a roof, or leaves in a breeze, or simply a deep, warm silence. Let it become the soundtrack of your rest.", pauseAfter: 18 },
      { text: "Feel the air of this place on your skin, the perfect temperature, neither too warm nor too cool. Feel the surface beneath you, made for your exact shape, receiving you completely, as if you had always belonged here.", pauseAfter: 18 },
      { text: "In this place, nothing is required of you. There are no tasks, no questions, no one to be. You are free to simply be here, quiet and still, like an animal at rest in a place it knows is safe.", pauseAfter: 18 },
      { text: "Let yourself settle deeper into this place, and notice how the body relaxes on its own, the way it always relaxes when it knows it is safe. The shoulders drop. The breath slows. The mind grows quiet.", pauseAfter: 18 },
      { text: "Stay here for a while, resting in this safety. You have been carrying so much, out in the world, staying alert, staying strong. But here, you can lay all of that down. Here, you are held.", pauseAfter: 20 },
      { text: "If the mind wanders, gently guide it back to this place, to its sounds and its soft light. You do not have to fight the wandering. You only have to return, again and again, as many times as it takes.", pauseAfter: 20 },
      { text: "Feel the safety of this place seeping into you, like warmth spreading through the body, until every part of you knows, without a doubt, that you are safe. You can let your guard down completely now.", pauseAfter: 20 },
      { text: "This place will always be here for you. You can return to it any night, any moment, whenever you need to feel held. It is yours, and no one can take it from you. Let that knowing settle deep into your bones.", pauseAfter: 20 },
      { text: "Now let this place begin to grow dim, like a room where the lamps are being turned down one by one. The colours soften, the sounds grow distant, and the warmth remains, wrapping around you like a blanket.", pauseAfter: 22 },
      { text: "You are slipping from this place into sleep, and it is all right to let go. The safety does not leave you. It goes with you, into the dark, into the rest, like a hand holding yours.", pauseAfter: 22 },
      { text: "If you are still awake, that is perfectly all right. Stay in the warmth, in the safety, in the quiet. There is nowhere else to be, and nothing else to do. Just rest, here, where you are safe.", pauseAfter: 22 },
      { text: "I will be quiet now, and leave you in your safe place, with its soft light and its deep quiet. Let yourself drift. Goodnight.", pauseAfter: 0 },
    ],
  },
  {
    id: "deep-sleep-reset-6",
    title: "Deep Sleep Reset — Night 6: Letting the Day Dissolve",
    description:
      "The sixth night. Watch the whole day dissolve like mist and surrender to the dark.",
    duration: "10 min",
    theme: "Deep Sleep Reset",
    category: "sleep",
    background: "off",
    introPause: 25,
    segments: [
      { text: "Welcome back. This is the sixth night of your deep sleep reset. Settle into bed, and let the body grow still. Tonight, we take everything the day has left behind, and we let it dissolve, like mist in the morning sun, until only rest remains.", pauseAfter: 14 },
      { text: "Take a slow breath in, and let it out with a long, soft sigh, as if you were releasing the very last of the day. Feel the sigh travel all the way through you, loosening whatever it touches, leaving you a little lighter.", pauseAfter: 16 },
      { text: "Now bring the day to mind, not to relive it, but simply to acknowledge it. See it as a long, winding ribbon of moments, now complete, now behind you. You lived it as well as you could. It is finished now.", pauseAfter: 17 },
      { text: "Let the conversations of the day dissolve. The words you said, the words left unsaid, the voices that lingered — let them all soften and fade, until they are nothing but a distant murmur, and then silence.", pauseAfter: 18 },
      { text: "Let the tasks of the day dissolve. The things you finished, the things left undone, the lists and the small pressures — let them all loosen and drift away, like leaves carried off by a slow river. They do not belong to the night.", pauseAfter: 18 },
      { text: "Let the emotions of the day dissolve. The moments of joy, the moments of frustration, the small hurts and the small victories — let them all pass through you and out, leaving you clear and still, like water after the sediment has settled.", pauseAfter: 18 },
      { text: "Notice how much lighter you feel, with each of these things released. The shoulders have dropped. The brow has smoothed. The body, which has been carrying the day, is finally allowed to set it down.", pauseAfter: 18 },
      { text: "With every breath out, let a little more of the day fall away, until there is almost nothing left of it, only the faintest trace, like the last warmth of the sun long after it has gone down.", pauseAfter: 18 },
      { text: "You are becoming lighter and lighter, emptier and emptier, the way the sky empties of birds at dusk. What remains is not emptiness, but spaciousness — a wide, quiet space where you can simply be.", pauseAfter: 20 },
      { text: "In this space, there is no yesterday and no tomorrow. There is only this moment, and the next breath, and the soft dark gathering around you. You are no longer the person who lived the day. You are simply presence, at rest.", pauseAfter: 20 },
      { text: "Let yourself float in this space, weightless and warm, held by the night itself. There is nothing to hold onto, and nothing that needs holding. You are free to drift, free to let go, free to be carried.", pauseAfter: 20 },
      { text: "If a thought of the day returns, do not engage it. Let it be like the last leaf of autumn, and watch it fall away into the dark. You have already said goodbye to it. You do not need to say it again.", pauseAfter: 20 },
      { text: "Feel how quiet everything has become. The body, soft and still. The mind, clear and calm. The day, gone. Only the night remains, and the night is gentle, and it is all for you.", pauseAfter: 22 },
      { text: "You have done enough. You have been enough. Whatever the day was, it is complete now, and you are free to rest. Let the last of it dissolve, and feel yourself sink into the welcome darkness.", pauseAfter: 22 },
      { text: "If you are still awake, simply rest in the spaciousness, in the quiet, in the dark. There is no test here, and no failing. Only the slow, sweet letting go.", pauseAfter: 22 },
      { text: "I will be quiet now, and leave you to the dark, and the quiet, and the deep, dissolving rest. Let yourself drift. Goodnight.", pauseAfter: 0 },
    ],
  },
  {
    id: "deep-sleep-reset-7",
    title: "Deep Sleep Reset — Night 7: The Deep Rest",
    description:
      "The final night. A long, deep descent into rest, and a gentle farewell to the journey.",
    duration: "10 min",
    theme: "Deep Sleep Reset",
    category: "sleep",
    background: "off",
    introPause: 25,
    segments: [
      { text: "Welcome back, for the last time. This is the seventh and final night of your deep sleep reset. Settle into bed, and take a moment to feel how far you have come. Seven nights of returning to yourself. Seven nights of letting go. Tonight, we simply rest, deep and complete.", pauseAfter: 15 },
      { text: "Take a slow breath in, and let it out with a soft sigh, releasing the day, releasing the week, releasing everything that no longer serves you. Feel the body answer with a deep, instinctive relaxation, as if it has been waiting for this.", pauseAfter: 16 },
      { text: "Bring your attention to the whole body, all at once, not part by part but as one single field of warmth and stillness. Notice how familiar this has become, this settling, this arriving. Your body knows the way now.", pauseAfter: 17 },
      { text: "Let your awareness travel slowly down from the crown of the head to the soles of the feet, lingering wherever there is still a little tension, and breathing it away. The forehead. The jaw. The shoulders. The belly. The legs. Let every part of you rest.", pauseAfter: 18 },
      { text: "Feel the breath, slow and deep, moving through you like a tide, and let it carry you down, down, into a deeper place than before. There is no rush, and no destination. Just the gentle, endless descent into rest.", pauseAfter: 18 },
      { text: "Tonight the mind is quiet almost on its own, the way it has learned to be over these seven nights. The thoughts are few and far between, like distant stars, and even they are beginning to fade.", pauseAfter: 18 },
      { text: "Let yourself feel the weight of the body, heavy and warm, sinking into the bed, into the earth, into the deep. And let yourself feel, at the same time, how light the mind has become, how free, how unburdened.", pauseAfter: 18 },
      { text: "You have learned, over these nights, how to let go — of the day, of the thoughts, of the need to hold on. And now, on this final night, you can let go of the letting go itself, and simply rest, the way you were always meant to.", pauseAfter: 20 },
      { text: "There is nothing left to practice, nothing left to reach for. The journey is complete, but it does not end here. It lives on in you, in the way you breathe, in the way you soften, in the way you return to yourself, night after night.", pauseAfter: 20 },
      { text: "Feel the deep rest moving through you now, like slow water through still ground, saturating every cell, every breath, every quiet corner of the mind. This is what you came for, and it is already here.", pauseAfter: 20 },
      { text: "Let the darkness become a comfort now, not something to be avoided, but something to be welcomed, the way a tired child welcomes sleep. It is soft, and it is safe, and it is waiting to hold you.", pauseAfter: 20 },
      { text: "With each breath out, sink a little deeper, until the boundary between you and the night grows thin, and you can no longer tell where one ends and the other begins. You are not disappearing. You are expanding, into rest.", pauseAfter: 22 },
      { text: "If you are still awake, that is all right. Rest is not something you achieve. It is something you allow. And you are allowing it, even now, in this very moment, simply by being here, breathing, letting go.", pauseAfter: 22 },
      { text: "Take with you, from these seven nights, this one thing: you can always return here. The breath is always with you. The quiet is always underneath. The rest is always waiting, patient and kind, whenever you are ready.", pauseAfter: 22 },
      { text: "Thank you for walking this path with me. You have done something gentle and true for yourself, and it matters more than you know. Now, let it all go, and let the deep rest carry you home.", pauseAfter: 22 },
      { text: "I will be quiet now, and leave you to the deep, to the dark, and to the rest you have so gently earned. Stay here as long as you like. Let yourself drift. Goodnight, and sleep well.", pauseAfter: 0 },
    ],
  },

  {
    id: "anxiety-to-ease-1",
    title: "From Anxiety to Ease — Session 1: Arriving",
    description:
      "The first session. Land gently in the present moment and let the day fall away.",
    duration: "10 min",
    theme: "From Anxiety to Ease",
    category: "relax",
    background: "off",
    introPause: 20,
    segments: [
      { text: "Welcome. This is the first session of From Anxiety to Ease. Find a comfortable position, sitting or lying down, and give yourself permission to simply arrive. You do not need to feel calm yet. You only need to be here, exactly as you are.", pauseAfter: 12 },
      { text: "Take one slow breath in, and let it out with a long, soft sigh. Notice how the body already knows how to release, how it wants to settle. You are not fighting anything. You are simply arriving, one breath at a time.", pauseAfter: 14 },
      { text: "Bring your attention to the places where your body is touching something — your feet on the floor, your back against the chair, your hands resting in your lap. Feel the ground holding you, steady and certain. You are supported.", pauseAfter: 14 },
      { text: "Now notice what is happening inside you, without needing to change any of it. There may be a tightness in the chest, a flutter in the belly, a busyness in the mind. Whatever is here, let it be here. It is welcome.", pauseAfter: 15 },
      { text: "Often, when anxiety is present, the first instinct is to push it away, to fix it, to make it stop. But tonight we do something different. We simply allow it to be here, and we watch it, with the same kindness you would offer a tired friend.", pauseAfter: 15 },
      { text: "Feel your feet again, heavy and rooted. Feel the slow rise and fall of your breath, moving on its own, without your effort. The breath has been with you through everything, and it is with you now.", pauseAfter: 14 },
      { text: "Let your attention rest on the breath, like a leaf resting on still water. Each time the mind wanders — and it will — gently bring it back, without judgment, without frustration. The returning is the practice.", pauseAfter: 15 },
      { text: "You are not your anxiety. You are the quiet awareness that notices it, the still space in which it appears. And that space is always here, always calm, always unhurried.", pauseAfter: 15 },
      { text: "With every breath out, let the shoulders drop a little more, let the jaw soften a little more, let the grip of the day loosen a little more. There is nothing to hold onto, and nothing to prove.", pauseAfter: 15 },
      { text: "Feel how the body begins to settle on its own, the way a stirred glass of water slowly grows still again. You do not have to make the stillness happen. You only have to stop stirring.", pauseAfter: 15 },
      { text: "If a worry arises, let it be like a wave rising and falling, and then returning to the sea. You are not the wave. You are the wide, calm ocean underneath it, always there, always steady.", pauseAfter: 15 },
      { text: "Rest here, in this wide, calm place, for as long as you like. The anxiety may still be present, but you are no longer tangled up in it. You are the one watching, and that changes everything.", pauseAfter: 15 },
      { text: "Notice how, even in these few minutes, something has already softened. A little more space, a little more ease. This is what happens when we stop fighting and simply arrive.", pauseAfter: 15 },
      { text: "Carry this sense of arrival with you as you move through your day. Whenever you feel the grip return, come back to the feet, the breath, the quiet space that is always here.", pauseAfter: 15 },
      { text: "There is nothing more to do right now. Just rest, breathe, and allow yourself to be exactly where you are. You are doing beautifully.", pauseAfter: 15 },
      { text: "I will be quiet now, and leave you with the breath and the stillness. Stay here as long as you like. You have arrived.", pauseAfter: 0 },
    ],
  },
  {
    id: "anxiety-to-ease-2",
    title: "From Anxiety to Ease — Session 2: The Breath as Anchor",
    description:
      "The second session. Use the breath as a steady anchor in the storm of the mind.",
    duration: "10 min",
    theme: "From Anxiety to Ease",
    category: "relax",
    background: "off",
    introPause: 20,
    segments: [
      { text: "Welcome back. This is the second session of From Anxiety to Ease. Settle into your position, and let your body find its ease. Today we turn to the breath, the one thing that is always with you, a steady anchor in the storm of the mind.", pauseAfter: 12 },
      { text: "Take a slow breath in through the nose, and let it out with a soft sigh. Notice the air moving in, cool and calm, and out, warm and soft. You do not have to change the breath. Just notice it, exactly as it is.", pauseAfter: 14 },
      { text: "When anxiety rises, the breath often becomes shallow and quick, high in the chest. And when the breath slows, the body gets a signal that it is safe. So tonight, we let the breath guide us back to safety, one slow cycle at a time.", pauseAfter: 14 },
      { text: "Breathe in slowly, and let the belly soften and expand, like a balloon filling gently. Then breathe out slowly, letting everything release, a little longer than the breath in. Feel the difference in your body already.", pauseAfter: 15 },
      { text: "Let each exhale be a small act of letting go. With every breath out, you are releasing a little tension, a little worry, a little of the grip that anxiety holds. You are allowed to soften here.", pauseAfter: 15 },
      { text: "Place one hand on your belly, if you like, and feel it rise and fall beneath your palm. The breath is doing this all by itself, without your effort, without your control. You can trust it.", pauseAfter: 14 },
      { text: "Now imagine the breath as a slow tide, moving in and out, in and out, steady and unhurried. You are not making the tide. You are simply floating on it, carried by its gentle rhythm.", pauseAfter: 15 },
      { text: "If the mind begins to race, do not fight it. Simply come back to the breath, again and again, the way you would return to the sound of the ocean. The breath is always here, patient and constant.", pauseAfter: 15 },
      { text: "Feel the cool air at the nostrils as you breathe in, and the warm air as you breathe out. This tiny sensation is a doorway into the present moment, and it is always open to you.", pauseAfter: 14 },
      { text: "With each cycle, let the breath grow a little slower, a little deeper, a little softer. You are teaching the body, gently, that it is safe to rest. And the body is listening.", pauseAfter: 15 },
      { text: "Notice how the thoughts begin to settle as the breath slows, the way dust settles when the wind dies down. You are not forcing the mind quiet. You are simply giving it a steadier rhythm to follow.", pauseAfter: 15 },
      { text: "Stay here with the breath, your anchor, for as long as you like. Whenever the mind wanders, the breath is there to bring you back, steady and kind, like a hand reaching out in the dark.", pauseAfter: 15 },
      { text: "Feel the deep sense of safety that comes from this slow, even breathing. The breath has kept you alive every moment of your life. It will not abandon you now. You can rest in it.", pauseAfter: 15 },
      { text: "As we come to a close, notice how the body feels compared to when we began. A little calmer, a little more spacious. This is the gift of the breath, and it is always available to you.", pauseAfter: 15 },
      { text: "Take one more slow breath in, and one long breath out. Carry the rhythm with you, and return to it whenever you need your anchor.", pauseAfter: 15 },
      { text: "I will be quiet now, and leave you with the steady tide of your breath. Stay here as long as you like. You are safe.", pauseAfter: 0 },
    ],
  },
  {
    id: "anxiety-to-ease-3",
    title: "From Anxiety to Ease — Session 3: Meeting the Mind",
    description:
      "The third session. Meet your anxious thoughts with kindness instead of resistance.",
    duration: "10 min",
    theme: "From Anxiety to Ease",
    category: "relax",
    background: "off",
    introPause: 20,
    segments: [
      { text: "Welcome back. This is the third session of From Anxiety to Ease. Settle in, and let the body grow still. Today we turn toward the mind, the place where anxiety does most of its work, and we meet it there, gently.", pauseAfter: 12 },
      { text: "Take a slow breath in, and let it out softly. For the next few minutes, we are not going to fight our thoughts, or silence them, or push them away. We are simply going to meet them, with curiosity and kindness.", pauseAfter: 14 },
      { text: "Bring to mind the way your thoughts have been lately. Perhaps they race, or repeat, or spin in circles around the same worries. Notice this without judgment. The mind is only trying to protect you, in its own way.", pauseAfter: 15 },
      { text: "Now imagine that each thought is a cloud, drifting across a wide sky. You are not the cloud. You are the sky — vast, open, and undisturbed by whatever passes through it.", pauseAfter: 15 },
      { text: "When a worried thought appears, instead of grabbing onto it, simply say to yourself, softly, there is a thought. And let it drift on, like a cloud, without following it, without fighting it.", pauseAfter: 15 },
      { text: "You do not have to believe every thought that arises. You can simply watch it, the way you would watch a leaf float down a river. It comes, and it goes. And you remain, quiet and still.", pauseAfter: 15 },
      { text: "Notice the space between thoughts, the small silences where the mind rests. These silences are always here, underneath the noise. They are the still water beneath the waves.", pauseAfter: 14 },
      { text: "If a thought is especially persistent, give it a gentle name — worrying, planning, remembering — and let the naming soften its grip. Naming a thought is like turning on a small light in a dark room.", pauseAfter: 15 },
      { text: "Remember that you are not your thoughts. You are the awareness that hears them, the quiet presence that watches them come and go. And that awareness is always calm, always whole, always at ease.", pauseAfter: 15 },
      { text: "Let the thoughts come and go at their own pace, without your interference. You do not have to manage them. You only have to let them be, and return, again and again, to the quiet presence that watches.", pauseAfter: 15 },
      { text: "Feel how, as you stop fighting the mind, the mind begins to quiet on its own. The waves settle, the clouds thin, and the sky grows wide and clear. This is what happens when we meet the mind with kindness.", pauseAfter: 15 },
      { text: "There is nothing you need to figure out right now, nothing to solve, nothing to fix. The answers can wait. For now, it is enough to simply be here, watching, breathing, allowing.", pauseAfter: 15 },
      { text: "Notice the growing sense of spaciousness inside you, the room that opens up when you stop wrestling with your thoughts. This spaciousness is your true nature, and it has always been here.", pauseAfter: 15 },
      { text: "As we close, carry this practice with you. The next time your thoughts spin, you can step back, watch them, and remember that you are the sky, not the clouds.", pauseAfter: 15 },
      { text: "Take one more slow breath in, and let it go. You have met the mind with kindness today, and that is no small thing.", pauseAfter: 15 },
      { text: "I will be quiet now, and leave you with the wide, clear sky of your own awareness. Stay here as long as you like.", pauseAfter: 0 },
    ],
  },
  {
    id: "anxiety-to-ease-4",
    title: "From Anxiety to Ease — Session 4: Releasing the Body",
    description:
      "The fourth session. Melt the physical tension that anxiety holds in the body.",
    duration: "10 min",
    theme: "From Anxiety to Ease",
    category: "relax",
    background: "off",
    introPause: 20,
    segments: [
      { text: "Welcome back. This is the fourth session of From Anxiety to Ease. Settle in, and let your body find its place. Today we turn our attention to the body, where anxiety is held as tension, and we invite it to release.", pauseAfter: 12 },
      { text: "Take a slow breath in, and let it out with a soft sigh. Notice where the body is holding on — the shoulders, the jaw, the belly, the brow. We are not going to force anything open. We are simply going to bring warmth and attention.", pauseAfter: 14 },
      { text: "Begin with the face. Let the forehead smooth, the space between the eyebrows release, the eyes grow heavy and soft. Unclench the jaw, and let the tongue rest gently. The face is softening already.", pauseAfter: 14 },
      { text: "Now the neck and the shoulders. Let the shoulders drop away from the ears, falling like warm water. Feel the weight of them settling, and breathe into any tightness there, letting the breath loosen what it touches.", pauseAfter: 15 },
      { text: "Bring your awareness to your chest, where anxiety often sits, like a tight band. Do not push against it. Simply breathe into it, softly, and imagine the breath creating space around it, softening its edges.", pauseAfter: 15 },
      { text: "Notice the belly, and let it soften, releasing the habit of bracing. With each breath out, let the belly fall, heavy and relaxed. You do not have to hold yourself together. You can let go.", pauseAfter: 15 },
      { text: "Let your attention travel down through the hips, the legs, and the feet, letting each part of you grow heavy and warm. Feel the body settling into the surface beneath you, held and supported.", pauseAfter: 15 },
      { text: "Scan the body once more, from head to toe, and wherever you find tension, breathe into it. Imagine the breath as warm light, reaching into the tight places, loosening them gently, patiently.", pauseAfter: 15 },
      { text: "Notice how the body responds to this attention, how it begins to soften and open, the way ice melts in warm water. You are not forcing the release. You are simply allowing it to happen.", pauseAfter: 15 },
      { text: "Feel the difference now between the body you arrived with and the body you are in now. A little looser, a little lighter, a little more at home. This is your birthright — to rest without tension.", pauseAfter: 15 },
      { text: "Let the breath continue to move through you, slow and steady, carrying away whatever remains. Each exhale releases a little more, until only a deep, quiet ease remains.", pauseAfter: 15 },
      { text: "If any tension returns, that is all right. It is not a failure. Simply notice it, breathe into it, and let it go again. The body has its own wisdom, and it will release when it is ready.", pauseAfter: 15 },
      { text: "Rest now in the softness of the body, the quiet of the breath, the ease of simply being. There is nowhere to go, nothing to hold, nothing to defend against. Just this gentle, living stillness.", pauseAfter: 15 },
      { text: "As we close, remember that the body is not your enemy. It is your home, and it has been carrying you through everything. Treat it with the same kindness you are learning to offer yourself.", pauseAfter: 15 },
      { text: "Take one more slow breath, and let it all go. Feel the ease settling into your bones, and carry it with you.", pauseAfter: 15 },
      { text: "I will be quiet now, and leave you with the softness of your own body, at rest. Stay here as long as you like.", pauseAfter: 0 },
    ],
  },
  {
    id: "anxiety-to-ease-5",
    title: "From Anxiety to Ease — Session 5: Ease",
    description:
      "The final session. Rest in the ease that has always been here, underneath everything.",
    duration: "10 min",
    theme: "From Anxiety to Ease",
    category: "relax",
    background: "off",
    introPause: 20,
    segments: [
      { text: "Welcome back, for the last time. This is the fifth and final session of From Anxiety to Ease. Settle in, and take a moment to feel how far you have come. Five sessions of turning toward yourself, of softening, of arriving. Today, we simply rest in ease.", pauseAfter: 12 },
      { text: "Take a slow breath in, and let it out with a long, soft sigh, releasing the day, releasing the week, releasing everything that no longer serves you. Feel the body answer with a deep, instinctive relaxation.", pauseAfter: 14 },
      { text: "You have learned, over these sessions, to arrive, to breathe, to meet your thoughts with kindness, and to release the body. And now, on this final session, you can let go of the practice itself, and simply rest in the ease that has always been here.", pauseAfter: 15 },
      { text: "Notice that the ease we have been seeking is not something you need to create. It is not something you need to earn, or achieve, or hold onto. It is already here, underneath everything, like still water beneath the waves.", pauseAfter: 15 },
      { text: "Feel the breath moving on its own, slow and even, and let yourself be carried by it. There is nothing to do, nothing to fix, nothing to become. Just this moment, and the next breath, and the quiet.", pauseAfter: 15 },
      { text: "Let the whole body soften now, from the crown of the head to the soles of the feet, until you are resting in a single field of quiet ease. The shoulders drop, the jaw releases, the mind grows still.", pauseAfter: 15 },
      { text: "Notice how the anxiety that once felt so loud has grown quiet in your presence. Not because you fought it, but because you stopped feeding it. What remains is spaciousness, and the gentle hum of simply being.", pauseAfter: 15 },
      { text: "You have discovered something true in these sessions — that you can be with difficulty without being consumed by it. That you are not your thoughts, not your tension, not your fear. You are the vast, calm awareness that holds it all.", pauseAfter: 15 },
      { text: "This ease does not leave you when the session ends. It goes with you, into your day, into your relationships, into the quiet corners of your life. It is a part of you now, and you can return to it whenever you need.", pauseAfter: 15 },
      { text: "When the old anxiety returns — and it may, from time to time — you will know what to do. You will arrive, you will breathe, you will meet your mind with kindness, and you will release the body. And underneath it all, you will find this ease, waiting.", pauseAfter: 15 },
      { text: "There is nothing you need to hold onto from these sessions. No technique to master, no state to maintain. The practices were only ever pointing you back to what was always true — that you are already whole, already at ease.", pauseAfter: 15 },
      { text: "Rest here, in this wholeness, for as long as you like. Let the breath be slow, the body be soft, the mind be still. This is your home, and you have always belonged here.", pauseAfter: 15 },
      { text: "Thank you for walking this path with yourself. You have done something gentle and true, and it matters more than you know. Now, let it all go, and rest in the ease.", pauseAfter: 15 },
      { text: "As we close, take one slow breath in, and one long breath out. Feel the ease settle into you, and know that it will not leave you. You carry it with you, always.", pauseAfter: 15 },
      { text: "There is nothing more to do now. Just rest, breathe, and allow yourself to be exactly as you are. You are enough, exactly as you are.", pauseAfter: 15 },
      { text: "I will be quiet now, and leave you with the ease, the breath, and the quiet. Stay here as long as you like. You have arrived.", pauseAfter: 0 },
    ],
  },

  {
    id: "sleep-story-lake",
    title: "The Quiet Lake",
    description:
      "A bedtime story — drift across a still lake under a fading sky.",
    duration: "15 min",
    theme: "Sleep Story",
    category: "sleep",
    background: "off",
    introPause: 20,
    segments: [
      { text: "Let your body settle into the bed, and let your eyes fall closed. We are going to travel somewhere quiet tonight, a place that exists only for you. A lake, at the end of the day, where the water is perfectly still and the sky is beginning to fade.", pauseAfter: 16 },
      { text: "Imagine a path of soft pine needles beneath your feet, winding down toward the water. The air is cool and clean, and it smells of earth and evening. Each step you take is slow, and unhurried, and your body grows a little heavier with every one.", pauseAfter: 16 },
      { text: "The trees part, and there it is — the lake, spread out before you like a sheet of dark glass. Not a ripple disturbs it. The water holds the last light of the sky, soft and grey and gold, and the world has gone very quiet.", pauseAfter: 16 },
      { text: "There is a small wooden dock at the water's edge, and you walk out onto it, and sit down. The wood is warm from the day, and it creaks softly beneath you. You let your legs dangle above the water, and you breathe.", pauseAfter: 16 },
      { text: "Across the lake, the last birds are settling into the trees, their calls growing fewer and softer, until only one remains, and then none at all. The silence that follows is deep and kind, and it seems to welcome you.", pauseAfter: 16 },
      { text: "You look down at the water, and you can see the sky reflected there, and the first faint stars beginning to appear. The reflection is so still that you can no longer tell which is the sky and which is the lake, and it does not matter anymore.", pauseAfter: 16 },
      { text: "A soft breeze moves across the water, barely enough to touch the surface, and it carries with it the sound of nothing at all — only the hush of the evening, and the slow rhythm of your own breath.", pauseAfter: 16 },
      { text: "You lie back on the dock, and the wood holds you like a hammock. Above you, the sky deepens from grey to blue to indigo, and one by one, the stars come out, like small lights being turned on in a dark room.", pauseAfter: 16 },
      { text: "The lake holds you too, somehow, even though you are not touching it. Its stillness has seeped into you, and you feel your thoughts settling the way the water settled, growing calm and clear and deep.", pauseAfter: 16 },
      { text: "You are not in a hurry anymore. There is nowhere else you need to be, and nothing else you need to do. Only the dock, and the water, and the wide, quiet sky, and the slow breathing of the world.", pauseAfter: 16 },
      { text: "The breeze touches your face, as soft as a hand, and you let your eyes grow heavier. The stars blur gently, and the edge of the world grows soft, and you feel yourself beginning to drift, like a boat unmoored on still water.", pauseAfter: 16 },
      { text: "The sound of the lake fades into the sound of your breath, and the sound of your breath fades into sleep. You are safe here, and you are held, and there is nothing more to do but let go.", pauseAfter: 16 },
      { text: "Let the quiet lake carry you now, into the deep, into the dark, into a rest as still and as wide as the water itself. Goodnight.", pauseAfter: 0 },
    ],
  },
  {
    id: "sleep-story-cabin",
    title: "The Mountain Cabin",
    description:
      "A bedtime story — snow falling outside a warm cabin in the mountains.",
    duration: "15 min",
    theme: "Sleep Story",
    category: "sleep",
    background: "off",
    introPause: 20,
    segments: [
      { text: "Let your body settle into the bed, and let your eyes fall closed. Tonight we travel to a small cabin in the mountains, a place of warmth and wood and slow-falling snow, where the world outside is hushed and far away.", pauseAfter: 16 },
      { text: "Imagine yourself walking up a snowy path in the blue light of evening, toward a cabin with a single warm window glowing gold. The snow crunches softly under your boots, and your breath makes small clouds in the cold air.", pauseAfter: 16 },
      { text: "You reach the door, and it opens, and the warmth spills out to meet you. You step inside, and close the door behind you, and the cold is left outside, where it belongs. The room smells of cedar and woodsmoke.", pauseAfter: 16 },
      { text: "There is a fire in the stone hearth, crackling softly, and a heavy blanket folded on a chair. You slip off your boots, and your coat, and you feel the tiredness of the day begin to melt away in the warmth.", pauseAfter: 16 },
      { text: "You settle into a chair by the fire, and pull the blanket over you, and you watch the flames move. They dance slowly, orange and gold, and the light they cast flickers across the wooden walls, warm and alive.", pauseAfter: 16 },
      { text: "Outside the window, the snow has begun to fall again, thick and soft, and each flake drifts down in its own slow silence. The whole world seems to be wrapping itself in white, and the quiet is deep and complete.", pauseAfter: 16 },
      { text: "You can hear the fire now, the soft pop and settle of the wood, and beyond it, the faint sound of the wind moving through the pines, low and far away. The cabin holds you, warm and safe, like a hand around a candle.", pauseAfter: 16 },
      { text: "The fire begins to burn low, and the room grows dim and golden, and you feel your eyelids growing heavy. The warmth has seeped into your bones, and the long day has finally begun to let go of you.", pauseAfter: 16 },
      { text: "You move to the small bed by the window, and the blankets are soft and worn, and they smell of cedar. You pull them up to your chin, and you can still see the snow falling through the window, silent and slow.", pauseAfter: 16 },
      { text: "The fire casts its last warm light across the ceiling, and the shadows sway gently, like the branches of the pines outside. You are warm, and you are safe, and the whole mountain is quiet around you.", pauseAfter: 16 },
      { text: "The snow continues to fall, soft and endless, and each flake seems to say, rest now, rest now. The cabin creaks once, softly, as if settling in for the night alongside you, and then all is still.", pauseAfter: 16 },
      { text: "You feel yourself sinking, deeper and deeper, into the warm, quiet dark. The fire, the snow, the mountain — they all fade gently, until only the sound of your own breath remains, slow and even.", pauseAfter: 16 },
      { text: "Let the mountain cabin carry you now, into the deep, into the dark, into a rest as warm and as quiet as the falling snow. Goodnight.", pauseAfter: 0 },
    ],
  },
  {
    id: "sleep-story-garden",
    title: "The Night Garden",
    description:
      "A bedtime story — wander a moonlit garden where every flower sleeps.",
    duration: "15 min",
    theme: "Sleep Story",
    category: "sleep",
    background: "off",
    introPause: 20,
    segments: [
      { text: "Let your body settle into the bed, and let your eyes fall closed. Tonight we wander into a garden at night, a secret place where the moon is bright and every flower is sleeping, and the air is soft with the scent of blossoms.", pauseAfter: 16 },
      { text: "Imagine a low stone wall, and a gate of weathered wood, and you push it open without a sound. The garden opens before you, silver and blue in the moonlight, and the path ahead is soft with fallen petals.", pauseAfter: 16 },
      { text: "You walk slowly along the path, and the grass is cool under your feet. On every side, the flowers are folded shut for the night, their colors muted in the moonlight, their heads bowed, sleeping.", pauseAfter: 16 },
      { text: "The air is thick with fragrance — jasmine and lavender and something sweet you cannot name — and it wraps around you like a soft shawl. With every breath, the garden seems to breathe with you, slow and calm.", pauseAfter: 16 },
      { text: "There is a stone bench beneath a flowering tree, and you sit down, and look up. The moonlight filters through the leaves, making patterns on the ground, and the petals drift down now and then, one at a time, like slow snow.", pauseAfter: 16 },
      { text: "Somewhere in the garden, a small fountain is trickling, a soft and endless sound, like the garden's own lullaby. The water catches the moonlight, and you can hear it, gentle and constant, beneath the stillness.", pauseAfter: 16 },
      { text: "A moth passes by, pale and silent, and you follow it with your eyes until it disappears into the shadows. The garden is full of small, quiet lives, all of them settling, all of them at rest.", pauseAfter: 16 },
      { text: "You feel the bench beneath you, and the cool night air on your skin, and the weight of your own body beginning to grow soft and heavy, as if the garden were gently pulling you toward sleep.", pauseAfter: 16 },
      { text: "The flowers around you seem to nod, one by one, and the tree above you rustles softly, as if to say, all is well, all is well. You are not a visitor here. You belong here, in this quiet, silver world.", pauseAfter: 16 },
      { text: "The moon climbs a little higher, and the garden grows stiller, and the path behind you fades into shadow. There is nothing you need to do, and nowhere you need to go. Only this bench, and this night, and this deep, fragrant calm.", pauseAfter: 16 },
      { text: "The fountain keeps its slow song, and the petals keep falling, and you let your eyes fall closed. The scent of the garden cradles you, and the moonlight rests on your face, cool and kind.", pauseAfter: 16 },
      { text: "You feel yourself drifting now, like a petal on the air, and the garden fades gently around you, until only the fragrance remains, and the sound of water, and the slow, soft breathing of the night.", pauseAfter: 16 },
      { text: "Let the night garden carry you now, into the deep, into the dark, into a rest as soft and as sweet as the sleeping flowers. Goodnight.", pauseAfter: 0 },
    ],
  },
];

/** Workshops as playable experiences — the existing player streams the guide
 *  audio at /api/meditations/audio/<workshop-id>.mp3, so `guide` = workshop id. */
export function workshopExperiences(): Experience[] {
  return WORKSHOPS.map((w) => ({
    id: w.id,
    category: w.category,
    title: w.title,
    description: w.description,
    duration: w.duration,
    guide: w.id,
    soundscape: "off",
    music: "temple-rain",
    scene: "night",
  }));
}
